[package]
name = "elec-sys"
version = "0.1.0"
edition = "2021"
authors = ["David Dunwoody <david.dunwoody@gmail.com>"]

[lib]
doctest = false

[features]
generate-bindings = ["dep:bindgen"]

[build-dependencies]
bindgen = { version = "0.65.1", optional = true }

[dev-dependencies]
acfutils-sys = { path = "../acfutils-sys" }
